/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findecursoproject.GUI;

import findecursoproject.Fecha;
import findecursoproject.MainController;
import findecursoproject.clsPersona;
import findecursoproject.extCliente;
import findecursoproject.extEmpleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import javax.swing.JCheckBox;
/**
 *
 * @author Nahuel
 */
public class frmPersona extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form frmPersona
     */
    public frmPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personaDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        personaName = new javax.swing.JTextField();
        personaApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        personaCI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        personaType = new javax.swing.JComboBox<>();
        personaExtra = new javax.swing.JPanel();
        preferencialCliente = new javax.swing.JCheckBox();
        fechaLabel = new javax.swing.JLabel();
        fechaMes = new javax.swing.JTextField();
        fechaDia = new javax.swing.JTextField();
        fechaAnio = new javax.swing.JTextField();
        catSelect = new javax.swing.JComboBox<>();
        catLabel = new javax.swing.JLabel();
        addPersona = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        personaDatos.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C.I:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de persona:");

        personaType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado" }));
        personaType.addActionListener(this);
        /*
        personaType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaTypeActionPerformed(evt);
            }
        });
        */

        javax.swing.GroupLayout personaDatosLayout = new javax.swing.GroupLayout(personaDatos);
        personaDatos.setLayout(personaDatosLayout);
        personaDatosLayout.setHorizontalGroup(
            personaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(personaName)
                    .addComponent(jLabel2)
                    .addComponent(personaApellido)
                    .addComponent(jLabel3)
                    .addComponent(personaCI)
                    .addComponent(jLabel4)
                    .addComponent(personaType, 0, 207, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        personaDatosLayout.setVerticalGroup(
            personaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personaCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        personaExtra.setBackground(new java.awt.Color(153, 153, 153));

        preferencialCliente.setVisible(false);
        preferencialCliente.setBackground(new java.awt.Color(153, 153, 153));
        preferencialCliente.setForeground(new java.awt.Color(255, 255, 255));
        preferencialCliente.setText("Preferencial?");
        preferencialCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencialClienteActionPerformed(evt);
            }
        });

        fechaLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("Fecha");

        catSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        catLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        catLabel.setForeground(new java.awt.Color(255, 255, 255));
        catLabel.setText("Categoria");

        javax.swing.GroupLayout personaExtraLayout = new javax.swing.GroupLayout(personaExtra);
        personaExtra.setLayout(personaExtraLayout);
        personaExtraLayout.setHorizontalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preferencialCliente)
                    .addComponent(fechaLabel)
                    .addGroup(personaExtraLayout.createSequentialGroup()
                        .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(catSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catLabel))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        personaExtraLayout.setVerticalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(preferencialCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addPersona.setBackground(new java.awt.Color(204, 204, 204));
        addPersona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPersona.setLabel("Añadir");
        addPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(addPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personaExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(addPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonaActionPerformed
        // TODO add your handling code here:
        clsPersona objPersona;
        String nombre = personaName.getText();
        String apellido = personaApellido.getText();
        String cedula = personaCI.getText();
        
        String select = personaType.getSelectedItem().toString();
        if(select.equals("Cliente")){
            boolean preferencial= preferencialCliente.isSelected();
          
            MainController.addPersonaCliente(preferencial,cedula,apellido,nombre,select);
            
            
            
        }
        
        
        else if(select.equals("Empleado")){
            String dia = fechaDia.getText();
            String mes = fechaMes.getText();
            String anio = fechaAnio.getText();
            String categoria = catSelect.getSelectedItem().toString();
            Fecha fecha = new Fecha(Integer.valueOf(dia),Integer.valueOf(mes),Integer.valueOf(anio));
             // objPersona = new extEmpleado(fecha,Integer.valueOf(categoria),cedula,apellido,nombre);
              MainController.addPersonaEmpleado(fecha,Integer.valueOf(categoria),cedula,apellido,nombre,select);
        }
        
    }//GEN-LAST:event_addPersonaActionPerformed

    private void personaTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaTypeActionPerformed
     
    }//GEN-LAST:event_personaTypeActionPerformed

    private void preferencialClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencialClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferencialClienteActionPerformed

    @Override
    public void actionPerformed(ActionEvent e){
         if(e.getSource() == personaType){
             String selected = personaType.getSelectedItem().toString();
             personaExtra.setVisible(false);
               personaExtra.removeAll();
             if(selected.equals("Cliente")){
                   javax.swing.GroupLayout personaExtraLayout = new javax.swing.GroupLayout(personaExtra);
        personaExtra.setLayout(personaExtraLayout);
                personaExtra.setVisible(true);
                preferencialCliente.setVisible(true);          
        personaExtraLayout.setHorizontalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preferencialCliente)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        personaExtraLayout.setVerticalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(preferencialCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
   
             
             
             }else if(selected.equals("Empleado")){
               
                  personaExtra.setVisible(true);
                  javax.swing.GroupLayout personaExtraLayout = new javax.swing.GroupLayout(personaExtra);
        personaExtra.setLayout(personaExtraLayout);
        
         personaExtraLayout.setHorizontalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               
                    .addComponent(fechaLabel)
                    .addGroup(personaExtraLayout.createSequentialGroup()
                        .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(catSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catLabel))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        personaExtraLayout.setVerticalGroup(
            personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaExtraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
               
                .addComponent(fechaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personaExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

                  
             }
        
         }
  }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addPersona;
    private javax.swing.JLabel catLabel;
    private javax.swing.JComboBox<String> catSelect;
    private javax.swing.JTextField fechaAnio;
    private javax.swing.JTextField fechaDia;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField personaApellido;
    private javax.swing.JTextField personaCI;
    private javax.swing.JPanel personaDatos;
    private javax.swing.JPanel personaExtra;
    private javax.swing.JTextField personaName;
    private javax.swing.JComboBox<String> personaType;
    private javax.swing.JCheckBox preferencialCliente;
    // End of variables declaration//GEN-END:variables
}
